TwitterClone/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('microblog.urls', namespace='microblog')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microblog/urls.py
from django.conf.urls import patterns, include, url
from microblog import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
	url(r'^detail/(?P<user>\d+)/$', views.detail, name='detail'),
	url(r'^addPost/(?P<profile_id>\d+)/$', views.addPost, name='addPost'),
	url(r'^follow/(?P<user_id>\d+)/$', views.follow, name='follow'),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^createProfile/$', views.createProfile, name="createProfile"),
    url(r'^updateProfile/$', views.updateProfile, name="updateProfile"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

microblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm, ModelChoiceField
from sorl.thumbnail import ImageField

class Profile(models.Model):
	user = models.ForeignKey(User)
	bio = models.TextField()
	pic = ImageField(upload_to='profile_pictures/')
	following = models.ManyToManyField('Profile', blank=True, null=True)

	def __unicode__(self):
		return self.user.username

class Post(models.Model):
	profile = models.ForeignKey(Profile)
	message = models.CharField(max_length=140)
	pub_date = models.DateTimeField(auto_now_add=True) 
	
	def __unicode__(self):
		return self.message

class PostForm(ModelForm):
	message = forms.CharField(widget=forms.Textarea)
	class Meta:
		model = Post
		fields = ['message']
	
	def __init__(self, *args, **kwargs):
		super(PostForm, self).__init__(*args,**kwargs)
		self.fields['message'].widget.attrs['class'] = "form-control"
		self.fields['message'].widget.attrs['rows'] = "4"

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = ['pic', 'bio']
		
class CreateForm(ModelForm):
	class Meta:
		model = Profile
		fields = ['pic', 'bio', 'following']

microblog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import ModelForm
from microblog.models import Profile, Post, PostForm, ProfileForm, CreateForm
from django.template import RequestContext

@login_required
def createProfile(request):
	try:
		profile = get_object_or_404(Profile, user=request.user.id)
		return HttpResponseRedirect('/')
	except:
		if request.method == 'POST':
			user = get_object_or_404(User, id=request.user.id)
			data = CreateForm(request.POST, request.FILES)
			form = data.save(commit=False)
			form.user = user
			form.save()
		else:
			profileForm = ProfileForm()
			context = {
				'profileForm': profileForm,
			}
			return render(request, 'microblog/createProfile.html', context)	
	return HttpResponseRedirect('/')	

@login_required
def index(request):
	try:
		profile = Profile.objects.get(user__username=request.user)
	except:
		return HttpResponseRedirect('/createProfile/')
	latestPosts = Post.objects.filter(profile__in=profile.following.all()).order_by('-pub_date')[:15]
	postForm = PostForm()
	context = {
		'latestPosts': latestPosts,
		'profile': profile,
		'postForm': postForm,
}
	return render(request, 'microblog/index.html', context)


@login_required
def profile(request):
	myProfile = get_object_or_404(Profile, user=request.user)
	following = myProfile.following	
	profileForm = ProfileForm()
	context = {
		'myProfile': myProfile,
		'following': following,
		'profileForm': profileForm,
	}
	return render(request, 'microblog/profile.html', context)

@login_required
def detail(request, user):
	latestPosts = Post.objects.all().filter(profile=user)
	profile = get_object_or_404(Profile, user=user)
	context = {
		'profile': profile,
		'latestPosts': latestPosts,
	}
	return render(request, 'microblog/detail.html', context)

@login_required
def addPost(request, profile_id):
	if request.method == 'POST':
		data = PostForm(request.POST)
		form = data.save(commit=False)
		form.profile = get_object_or_404(Profile, id=profile_id)
		form.save()
		if request.is_ajax():
			profile = get_object_or_404(Profile, id=profile_id) 
			latestPosts = Post.objects.filter(profile__in=profile.following.all()).order_by('-pub_date')[:15]
			context = {
				'profile': profile,
				'latestPosts': latestPosts,
			}		
			return render_to_response('microblog/newPost.html', context, context_instance=RequestContext(request))
	return HttpResponseRedirect('/')

@login_required
def updateProfile(request):
	if request.method == 'POST':
		profile = get_object_or_404(Profile, user=request.user.id)
		form = ProfileForm(request.POST, request.FILES, instance=profile)
		form.save()
	return HttpResponseRedirect('/')

@login_required
def follow(request, user_id):
	myProfile = get_object_or_404(Profile, user=request.user)
	profile = get_object_or_404(Profile, user=user_id)
	myProfile.following.add(profile)
	return HttpResponseRedirect('/')

TwitterClone/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} Twitter Clone {% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <!-- see http://netdna.bootstrapcdn.com/#bootswatch for some other "flavors" to try -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        
		<!-- Latest compiled and minified JavaScript -->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

        <style type="text/css">
        	body {padding: 50px 0 0 0; margin: 0; background-color: #8ec1da;}
			.lightBlue {background-color: #c0deed; padding-top: 10px;}
			.copyright {margin-top: 10px;}
			.panel {-webkit-border-radius: 7px; -moz-border-radius: 7px; border-radius: 7px;}
			.panel-body h3 {margin: 0; padding: 0;}
		</style>
		
        {% block extrascripts %}{% endblock %}
    </head>
    <body>
		<!-- Static navbar -->
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a href="/"><span class="glyphicon glyphicon-home"> Home</span></a></li>

                   		{% if user.is_authenticated %}
							<li><a href="{% url 'microblog:detail' user.id %}"><span class="glyphicon glyphicon-user"> Me</span></a></li>
                    	{% endif %}
					</ul>
					<ul class="nav navbar-nav navbar-right">
                   		{% if user.is_authenticated %}
							<li><a href="{% url 'microblog:profile' %}">Profile</a></li>
							<li><a href="/admin/">Admin</a></li>
							<li><a href="{% url 'auth_logout' %}">Sign Out</a></li>
						{% else %}
							<li><a href="{% url 'auth_login' %}">Sign In</a></li>
                    	{% endif %}
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
		<div class="container lightBlue">
			<div class="body-content">
				{% block content %}
            	{% endblock %}
			</div><!-- body-content -->
		</div><!-- container -->
		<div class="container text-center copyright">
			Travis Hunt &copy; Copyright 2013 
		</div>
	</body>
<html>

microblog/templates/microblog/createProfile.html
{% extends 'base.html' %}

{% block title %}Create a profile{% endblock %}

{% block content %}
	<form enctype="multipart/form-data" action="{% url 'microblog:createProfile' %}" method="POST" id="createForm" name="createForm">
	{% csrf_token %}
	<table class="table">
	{{ profileForm.as_table }}
	<tr><th></th><td class="text-right" >
	<button type="submit" class="btn btn-primary">Create Profile</button>
	</td></tr></table>
	</form>
{% endblock %}

microblog/templates/microblog/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load follow %}

{% block title %}Twitter Clone{% endblock %}

{% block content %}
	<table cellpadding="5" width="100%">
		<tr>

<!-- LEFT COLUMN -->
			<td valign="top" width="35%">
				<div class="list-group">
					<div class="list-group-item">
						<div class="clearfix">
							<div class="pull-left">
							{% thumbnail profile.pic "50x50" crop="bottom" as image %}
								<img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}">
							{% empty %}
								<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
							{% endthumbnail %}
							</div>
							<div class="pull-left">
								<strong> &nbsp; {{ profile.user }}</strong>
							</div>
						</div>
					</div>				
					<div class="list-group-item">
						<strong>About {{ profile.user }}</strong>
					</div>
					<div class="list-group-item">
						<p style="margin-left: 10px">
							{{ profile.bio }}
						</p>
					</div>
				</div>
				{% listProfiles %}
			</td>

<!-- RIGHT COLUMN -->
			<td valign="top">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Recent Posts by {{ profile.user }}</h3>
					</div>
					<table class="table">
<!-- TWEETS START -->
{% for post in latestPosts %}
	<tr>
		<td>
			<div class="clearfix">
				<!--  IMAGE -->
				<div class="pull-left">
					{% thumbnail post.profile.pic "50x50" crop="center" as image %}
						<img src="{{ image.url }}">
					{% empty %}
						<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
					{% endthumbnail %}
				</div>
				<!-- POST -->
				<div class="pull-left" style="padding-left: 10px">
					<div>
						<strong>{{ post.profile.user }}</strong>
					</div>
					<div>
						{{ post }}
					</div>
				</div>
				<!-- DATE -->
				<div class="pull-right">
					<span style="color: #999999; font-size: .75em;" class="pull-right">{{ post.pub_date }}</span>
				</div>
			</div>
		</td>
	</tr>
{% endfor %}
<!-- TWEETS END -->
					</table>
				</div>
			</td>
		</tr>
	</table>
{% endblock %}

microblog/templates/microblog/follow.html
<div class="list-group">
	<div class="list-group-item">
		<strong>People to follow:</strong>
	</div>
{% for profile in profiles %}
<a style="padding-left: 30px" class="list-group-item" href="{% url 'microblog:follow' profile.id %}">{{ profile }}</a>
{% endfor %}
</div>

microblog/templates/microblog/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load follow %}

{% block title %}Twitter Clone{% endblock %}

{% block extrascripts %}
<script>
$(function(){
	$("#tweet").submit(function(e){
		e.preventDefault();
		$.ajax({
			url: $(this).attr('action'),
			type: "post",
			data: $(this).serialize(),
			success: function(d) {
				$('#tweet')[0].reset();
				$('#posts').html(d);	
			},
			error: function(d){
				console.log(d);
			},
		});
		return false;
	});	
});
</script>
{% endblock %}

{% block content %}
	<table cellpadding="5" width="100%">
		<tr>

<!-- LEFT COLUMN -->
			<td valign="top" width="35%">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="clearfix">
							<div class="pull-left">
							{% thumbnail profile.pic "50x50" crop="bottom" as image %}
								<img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}">
							{% empty %}
								<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
							{% endthumbnail %}
							</div>
							<div class="pull-left">
								<strong> &nbsp; {{ profile.user }}</strong>
								<br>
								<a href="{% url 'microblog:profile' %}"><span style="padding-left: 10px; font-size: .8em; color: #999999;">view profile</span></a>
							</div>
						</div>
					</div>	
					<table class="table">
						<tr>
							<td>
								<form method="POST" action="{% url 'microblog:addPost' profile.id %}" name="tweet" id="tweet">
									{% csrf_token %}
									{{ postForm.as_p }}
									<div class="clearfix" style="margin-top: 8px;">
										<button class="btn btn-primary pull-right">Post Message</button>
									</div>
								</form>
							</td>
						</tr>
					</table>
				</div>
				{% listProfiles %}
			</td>

<!-- RIGHT COLUMN -->
			<td valign="top">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Recent Posts</h3>
					</div>
					<table id="posts" class="table">
<!-- TWEETS START -->
{% for post in latestPosts %}
	<tr>
		<td>
			<div class="clearfix">
				<!--  IMAGE -->
				<div class="pull-left">
					{% thumbnail post.profile.pic "50x50" crop="center" as image %}
						<img src="{{ image.url }}">
					{% empty %}
						<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
					{% endthumbnail %}
				</div>
				<!-- POST -->
				<div class="pull-left" style="padding-left: 10px">
					<div>
						<a href="{% url 'microblog:detail' post.profile.user.id %}"><strong>{{ post.profile.user }}</strong></a>
					</div>
					<div>
						{{ post }}
					</div>
				</div>
				<!-- DATE -->
				<div class="pull-right">
					<span style="color: #999999; font-size: .75em;" class="pull-right">{{ post.pub_date }}</span>
				</div>
			</div>
		</td>
	</tr>
{% endfor %}
<!-- TWEETS END -->
					</table>
				</div>
			</td>
		</tr>
	</table>
{% endblock %}

microblog/templates/microblog/newPost.html
{% load thumbnail %}

{% for post in latestPosts %}
<table id="posts" class="table">
	<tr>
		<td>
			<div class="clearfix">
				<!--  IMAGE -->
				<div class="pull-left">
					{% thumbnail post.profile.pic "50x50" crop="center" as image %}
						<img src="{{ image.url }}">
					{% empty %}
						<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
					{% endthumbnail %}
				</div>
				<!-- POST -->
				<div class="pull-left" style="padding-left: 10px">
					<div>
						<a href="{% url 'microblog:detail' post.profile.user.id %}"><strong>{{ post.profile.user }}</strong></a>
					</div>
					<div>
						{{ post }}
					</div>
				</div>
				<!-- DATE -->
				<div class="pull-right">
					<span style="color: #999999; font-size: .75em;" class="pull-right">{{ post.pub_date }}</span>
				</div>
			</div>
		</td>
	</tr>
</table>
{% endfor %}

microblog/templates/microblog/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load staticfiles %}
{% load follow %}

{% block title %}My Profile{% endblock %}

{% block content %}
	<table cellpadding="5" width="100%">
		<tr>
<!-- LEFT COLUMN -->
			<td valign="top" width="35%">
				<div class="list-group">
					<div class="list-group-item">
						<div class="clearfix">
							<div class="pull-left">
							{% thumbnail myProfile.pic "50x50" crop="bottom" as image %}
								<img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}">
							{% empty %}
								<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
							{% endthumbnail %}
							</div>
							<div class="pull-left">
								<strong> &nbsp; {{ myProfile.user }}</strong>
							</div>
						</div>
					</div>	
					<div class="list-group-item">		
						{% if following.count > 0 %}
							<strong>Following</strong>
						{% else %}
							<strong>Follow Someone!</strong>
						{% endif %}
					</div>		
					<!-- LIST OF FOLLOWING -->
					{% for user in following.all %}
						<a style="padding-left: 30px" class="list-group-item" href="{% url 'microblog:detail' user.id %}">{{ user }}<span class="pull-right"><strong>>></strong></span></a>
					{% endfor %}
				</div>
				{% listProfiles %}
			</td>
<!-- RIGHT COLUMN -->
			<td valign="top">
				<div class="panel panel-default">
					<div class="panel-body">
						<h3>Profile for {{ myProfile.user }}</h3>
					</div>
			       <form enctype="multipart/form-data" action="{% url 'microblog:updateProfile' %}" method="POST" id="updateForm" name="updateForm">
						{% csrf_token %}
					<table class="table">
<!-- PROFILE START -->
						<tr>
							<td>
								{% thumbnail myProfile.pic "50x50" crop="bottom" as image %}
									<img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}">
								{% empty %}
									<img src="/media/profile_pictures/generic-profile-pic.jpg" width="50" height="50" />
								{% endthumbnail %}
		
								{{ profileForm.as_p }}
							</td>
						</tr>
						<tr>
							<td class="text-center">
								<button type="submit" class="btn btn-primary">Update Profile</button>	
							</td>
						</tr>
<!-- PROFILE END -->
					</table>
					</form>
				</div>
			</td>
		</tr>
	</table>
{% endblock %}